from datetime import datetime
from sqlalchemy import Boolean, Column, DateTime, Float, ForeignKey, Integer, String, Text
from sqlalchemy.orm import relationship
from database import Base
class User(Base):
    __tablename__='users'; id=Column(Integer,primary_key=True); username=Column(String,nullable=False); email=Column(String,unique=True,index=True,nullable=False); password_hash=Column(String,nullable=False); created_at=Column(DateTime,default=datetime.utcnow); updated_at=Column(DateTime,default=datetime.utcnow,onupdate=datetime.utcnow)
    cameras=relationship('CameraSource',back_populates='user',cascade='all, delete-orphan'); sessions=relationship('MonitoringSession',cascade='all, delete-orphan'); events=relationship('Event',cascade='all, delete-orphan'); chats=relationship('ChatMessage',cascade='all, delete-orphan')
class CameraSource(Base):
    __tablename__='camera_sources'; id=Column(Integer,primary_key=True); user_id=Column(Integer,ForeignKey('users.id',ondelete='CASCADE'),nullable=False); name=Column(String,nullable=False); rtsp_url=Column(Text,nullable=False); mediamtx_path=Column(String,nullable=False); play_url=Column(Text,nullable=False); status=Column(String,default='connected'); created_at=Column(DateTime,default=datetime.utcnow); updated_at=Column(DateTime,default=datetime.utcnow,onupdate=datetime.utcnow); last_checked_at=Column(DateTime); last_error=Column(Text)
    user=relationship('User',back_populates='cameras'); sessions=relationship('MonitoringSession',back_populates='camera',cascade='all, delete-orphan'); actors=relationship('Actor',cascade='all, delete-orphan'); objects=relationship('TrackedObject',cascade='all, delete-orphan'); events=relationship('Event',cascade='all, delete-orphan'); chats=relationship('ChatMessage',cascade='all, delete-orphan')
class MonitoringSession(Base):
    __tablename__='monitoring_sessions'; id=Column(Integer,primary_key=True); camera_id=Column(Integer,ForeignKey('camera_sources.id',ondelete='CASCADE'),nullable=False); user_id=Column(Integer,ForeignKey('users.id',ondelete='CASCADE'),nullable=False); status=Column(String,default='running'); started_at=Column(DateTime,default=datetime.utcnow); stopped_at=Column(DateTime); frames_processed=Column(Integer,default=0); events_detected=Column(Integer,default=0); detected_people_count=Column(Integer,default=0); error_message=Column(Text)
    camera=relationship('CameraSource',back_populates='sessions'); actors=relationship('Actor',cascade='all, delete-orphan'); objects=relationship('TrackedObject',cascade='all, delete-orphan'); events=relationship('Event',back_populates='session',cascade='all, delete-orphan')
class Actor(Base):
    __tablename__='actors'; id=Column(Integer,primary_key=True); session_id=Column(Integer,ForeignKey('monitoring_sessions.id',ondelete='CASCADE')); camera_id=Column(Integer,ForeignKey('camera_sources.id',ondelete='CASCADE')); track_id=Column(String); first_seen_at=Column(Float); last_seen_at=Column(Float); traits_json=Column(Text); created_at=Column(DateTime,default=datetime.utcnow)
class TrackedObject(Base):
    __tablename__='tracked_objects'; id=Column(Integer,primary_key=True); session_id=Column(Integer,ForeignKey('monitoring_sessions.id',ondelete='CASCADE')); camera_id=Column(Integer,ForeignKey('camera_sources.id',ondelete='CASCADE')); object_track_id=Column(String); object_type=Column(String); first_seen_at=Column(Float); last_seen_at=Column(Float); last_owner_actor_id=Column(Integer); current_owner_actor_id=Column(Integer); is_stationary=Column(Boolean,default=False); created_at=Column(DateTime,default=datetime.utcnow)
class Event(Base):
    __tablename__='events'; id=Column(Integer,primary_key=True); user_id=Column(Integer,ForeignKey('users.id',ondelete='CASCADE'),nullable=False); camera_id=Column(Integer,ForeignKey('camera_sources.id',ondelete='CASCADE'),nullable=False); session_id=Column(Integer,ForeignKey('monitoring_sessions.id',ondelete='CASCADE')); actor_id=Column(Integer); object_id=Column(Integer); event_type=Column(String,index=True); scenario=Column(String,index=True); timestamp_seconds=Column(Float); timestamp_label=Column(String); confidence=Column(Float); description=Column(Text); traits_json=Column(Text); metadata_json=Column(Text); created_at=Column(DateTime,default=datetime.utcnow)
    session=relationship('MonitoringSession',back_populates='events')
class ChatMessage(Base):
    __tablename__='chat_messages'; id=Column(Integer,primary_key=True); user_id=Column(Integer,ForeignKey('users.id',ondelete='CASCADE')); camera_id=Column(Integer,ForeignKey('camera_sources.id',ondelete='CASCADE')); role=Column(String); content=Column(Text); citations_json=Column(Text); created_at=Column(DateTime,default=datetime.utcnow)
